version: '3.8'

services:
  python-app:
    build: .
    container_name: python_app_container
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
    command: python app.py
    ports:
      - "8000:8000"  # sesuaikan jika app kamu pakai port
